#!/bin/bash

# Slidev Setup Script
# This script initializes a new Slidev project for the AI agent to use

set -e  # Exit on error

PROJECT_ROOT="/Users/petereijgermans/Desktop/mcp-tutorial-java-magazine"
SLIDES_DIR="$PROJECT_ROOT/my-slides"

echo "🚀 Initializing Slidev project..."

# 1. Initialize a new Slidev project (non-interactive)
# We use 'npx' to create the project in a folder named 'my-slides'
if [ ! -d "$SLIDES_DIR" ]; then
    echo "📦 Creating new Slidev project..."
    cd "$PROJECT_ROOT"
    npx create-slidev@latest my-slides --yes
    
    # Move into the project directory
    cd "$SLIDES_DIR"
else
    echo "📁 Slidev project already exists, updating..."
    cd "$SLIDES_DIR"
fi

# 2. Create a placeholder slides.md if it doesn't exist
# This is where your AI agent will write its content later
if [ ! -f slides.md ]; then
    echo "📝 Creating initial slides.md..."
    cat <<'EOF' > slides.md
---
theme: seriph
background: https://source.unsplash.com/collection/94734566/1920x1080
class: text-center
highlighter: shiki
info: |
  ## Slidev Tutorial
  Generated by AI Agent
---

# Welcome to Slidev
The AI Agent will update these slides shortly.

---

# Preparation
The environment is ready for the Firecrawl + Slidev flow.
EOF
else
    echo "✅ slides.md already exists"
fi

# 3. Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "📦 Installing dependencies..."
    npm install
fi

echo ""
echo "✅ Setup complete!"
echo "📁 Slides location: $SLIDES_DIR/slides.md"
echo "💡 To start the live preview, run: cd $SLIDES_DIR && npm run dev"
echo "🌐 The slides will be available at: http://localhost:3030"


